package genesis.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPolissoir extends ModelBase {
    public ModelRenderer grooveBase;
    public ModelRenderer grooveBaseBend;
    public ModelRenderer grooveBaseSmall;
    public ModelRenderer base1;
    public ModelRenderer base2;
    public ModelRenderer base3;
    public ModelRenderer base4;
    public ModelRenderer baseBend1;
    public ModelRenderer baseBend2;
    public ModelRenderer baseBend3;
    public ModelRenderer baseBend4;
    public ModelRenderer water;
    public ModelRenderer grooveSeparator;
    public ModelRenderer grooveLength1;
    public ModelRenderer grooveLength2;
    public ModelRenderer grooveLength3;
    public ModelRenderer corner1;
    public ModelRenderer grooveLength4;
    public ModelRenderer grooveLength5;
    public ModelRenderer grooveLength6;
    public ModelRenderer corner2;
    public ModelRenderer corner3;
    public ModelRenderer corner4;
    public ModelRenderer corner5;
    public ModelRenderer corner6;
    public ModelRenderer corner7;
    public ModelRenderer corner8;
    public ModelRenderer grovesBaseBend;

    public ModelPolissoir() {
        textureWidth = 64;
        textureHeight = 128;

        grooveBase = new ModelRenderer(this, 0, 0);
        grooveBase.addBox(0F, 0F, 0F, 10, 9, 14);
        grooveBase.setRotationPoint(-8F, 15F, -6F);
        grooveBase.mirror = true;
        setRotation(grooveBase, 0F, 0F, 0F);
        grooveBaseBend = new ModelRenderer(this, 38, 24);
        grooveBaseBend.addBox(0F, 0F, 0F, 10, 3, 3);
        grooveBaseBend.setRotationPoint(-7.9F, 14F, -6F);
        grooveBaseBend.mirror = true;
        setRotation(grooveBaseBend, -0.7330383F, 0F, 0F);
        grooveBaseSmall = new ModelRenderer(this, 33, 31);
        grooveBaseSmall.addBox(0F, 0F, 0F, 9, 8, 2);
        grooveBaseSmall.setRotationPoint(-8F, 16.2F, -8F);
        grooveBaseSmall.mirror = true;
        setRotation(grooveBaseSmall, 0F, 0F, 0F);
        base1 = new ModelRenderer(this, 0, 24);
        base1.addBox(0F, 0F, 0F, 7, 9, 10);
        base1.setRotationPoint(1F, 15F, -8F);
        base1.mirror = true;
        setRotation(base1, 0F, 0F, 0F);
        base2 = new ModelRenderer(this, 0, 43);
        base2.addBox(0F, 0F, 0F, 6, 7, 6);
        base2.setRotationPoint(2F, 17F, 2F);
        base2.mirror = true;
        setRotation(base2, 0F, 0F, 0F);
        base3 = new ModelRenderer(this, 0, 57);
        base3.addBox(0F, 0F, 0F, 6, 2, 1);
        base3.setRotationPoint(1.9F, 15F, 7F);
        base3.mirror = true;
        setRotation(base3, 0F, 0F, 0.0523599F);
        base4 = new ModelRenderer(this, 14, 57);
        base4.addBox(0F, 0F, 0F, 1, 2, 5);
        base4.setRotationPoint(6.9F, 15F, 2F);
        base4.mirror = true;
        setRotation(base4, -0.0523599F, 0F, 0F);
        baseBend1 = new ModelRenderer(this, 27, 56);
        baseBend1.addBox(0F, 0F, 0F, 1, 3, 5);
        baseBend1.setRotationPoint(1F, 15.2F, 2F);
        baseBend1.mirror = true;
        setRotation(baseBend1, 0F, 0F, -0.6108652F);
        baseBend2 = new ModelRenderer(this, 0, 60);
        baseBend2.addBox(0F, 0F, -1F, 5, 3, 1);
        baseBend2.setRotationPoint(2F, 15F, 2F);
        baseBend2.mirror = true;
        setRotation(baseBend2, 0.6981317F, 0F, 0F);
        baseBend3 = new ModelRenderer(this, 27, 51);
        baseBend3.addBox(0F, 0F, 0F, 5, 3, 1);
        baseBend3.setRotationPoint(2F, 15F, 7F);
        baseBend3.mirror = true;
        setRotation(baseBend3, -0.6108652F, 0F, 0.0523599F);
        baseBend4 = new ModelRenderer(this, 27, 42);
        baseBend4.addBox(0F, 0F, 0F, 1, 3, 5);
        baseBend4.setRotationPoint(7F, 15F, 2F);
        baseBend4.mirror = true;
        setRotation(baseBend4, -0.0872665F, 0.0523599F, 0.715585F);
        water = new ModelRenderer(this, 40, 58);
        water.addBox(0F, 0F, 0F, 5, 1, 5);
        water.setRotationPoint(2F, 15.5F, 2F);
        water.mirror = true;
        setRotation(water, 0F, 0F, 0F);
        grooveSeparator = new ModelRenderer(this, 0, 65);
        grooveSeparator.addBox(0F, 0F, 0F, 2, 1, 14);
        grooveSeparator.setRotationPoint(0F, 14F, -6F);
        grooveSeparator.mirror = true;
        setRotation(grooveSeparator, 0F, 0F, 0F);
        grooveLength1 = new ModelRenderer(this, 33, 65);
        grooveLength1.addBox(0F, 0F, 0F, 10, 1, 1);
        grooveLength1.setRotationPoint(-8F, 14F, -6F);
        grooveLength1.mirror = true;
        setRotation(grooveLength1, 0F, 0F, 0F);
        grooveLength2 = new ModelRenderer(this, 33, 82);
        grooveLength2.addBox(0F, 0F, 0F, 8, 1, 1);
        grooveLength2.setRotationPoint(-8F, 14F, 7F);
        grooveLength2.mirror = true;
        setRotation(grooveLength2, 0F, 0F, 0F);
        //grooveLength3.mirror = true;
        grooveLength3 = new ModelRenderer(this, 33, 68);
        grooveLength3.addBox(0F, 0F, 0F, 1, 1, 12);
        grooveLength3.setRotationPoint(-8F, 14F, -5F);
        //grooveLength3.mirror = true;
        setRotation(grooveLength3, 0F, 0F, 0F);
        //grooveLength3.mirror = false;
        corner1 = new ModelRenderer(this, 0, 81);
        corner1.addBox(0F, 0F, 0F, 3, 1, 1);
        corner1.setRotationPoint(-2F, 14.1F, -4F);
        corner1.mirror = true;
        setRotation(corner1, 0F, 0.6981317F, 0F);
        grooveLength4 = new ModelRenderer(this, 0, 81);
        grooveLength4.addBox(0F, 0F, 0F, 1, 1, 12);
        grooveLength4.setRotationPoint(-2F, 14F, -5F);
        grooveLength4.mirror = true;
        setRotation(grooveLength4, 0F, 0.0523599F, 0F);
        grooveLength5 = new ModelRenderer(this, 27, 85);
        grooveLength5.addBox(0F, 0F, 0F, 1, 1, 12);
        grooveLength5.setRotationPoint(-4F, 14F, -5F);
        grooveLength5.mirror = true;
        setRotation(grooveLength5, 0F, 0.0523599F, 0F);
        grooveLength6 = new ModelRenderer(this, 0, 95);
        grooveLength6.addBox(0F, 0F, 0F, 1, 1, 12);
        grooveLength6.setRotationPoint(-6F, 14F, -5F);
        grooveLength6.mirror = true;
        setRotation(grooveLength6, 0F, 0.0349066F, 0F);
        corner2 = new ModelRenderer(this, 0, 83);
        corner2.addBox(0F, 0F, 0F, 3, 1, 1);
        corner2.setRotationPoint(-4F, 14.1F, -4F);
        corner2.mirror = true;
        setRotation(corner2, 0F, 0.6981317F, 0F);
        corner3 = new ModelRenderer(this, 0, 85);
        corner3.addBox(0F, 0F, 0F, 3, 1, 1);
        corner3.setRotationPoint(-6F, 14.1F, -4F);
        corner3.mirror = true;
        setRotation(corner3, 0F, 0.6981317F, 0F);
        corner4 = new ModelRenderer(this, 0, 87);
        corner4.addBox(0F, 0F, 0F, 3, 1, 1);
        corner4.setRotationPoint(-8F, 14.1F, -4F);
        corner4.mirror = true;
        setRotation(corner4, 0F, 0.6981317F, 0F);
        corner5 = new ModelRenderer(this, 18, 81);
        corner5.addBox(0F, 0F, 0F, 1, 1, 3);
        corner5.setRotationPoint(-1.5F, 14.1F, 5.7F);
        corner5.mirror = true;
        setRotation(corner5, 0F, 0.6981317F, 0F);
        corner6 = new ModelRenderer(this, 18, 85);
        corner6.addBox(0F, 0F, 0F, 1, 1, 3);
        corner6.setRotationPoint(-3.5F, 14.1F, 5.7F);
        corner6.mirror = true;
        setRotation(corner6, 0F, 0.6981317F, 0F);
        corner7 = new ModelRenderer(this, 0, 95);
        corner7.addBox(0F, 0F, 0F, 1, 1, 3);
        corner7.setRotationPoint(-5.5F, 14.1F, 5.7F);
        corner7.mirror = true;
        setRotation(corner7, 0F, 0.6981317F, 0F);
        corner8 = new ModelRenderer(this, 0, 99);
        corner8.addBox(0F, 0F, 0F, 1, 1, 3);
        corner8.setRotationPoint(-8F, 14.1F, 5.7F);
        corner8.mirror = true;
        setRotation(corner8, 0F, 0.6981317F, 0F);
        grovesBaseBend = new ModelRenderer(this, 0, 109);
        grovesBaseBend.addBox(0F, 0F, 0F, 7, 1, 12);
        grovesBaseBend.setRotationPoint(-7F, 14.9F, -5F);
        grovesBaseBend.mirror = true;
        setRotation(grovesBaseBend, 0.0523599F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        grooveBase.render(f5);
        grooveBaseBend.render(f5);
        grooveBaseSmall.render(f5);
        base1.render(f5);
        base2.render(f5);
        base3.render(f5);
        base4.render(f5);
        baseBend1.render(f5);
        baseBend2.render(f5);
        baseBend3.render(f5);
        baseBend4.render(f5);
        water.render(f5);
        grooveSeparator.render(f5);
        grooveLength1.render(f5);
        grooveLength2.render(f5);
        grooveLength3.render(f5);
        corner1.render(f5);
        grooveLength4.render(f5);
        grooveLength5.render(f5);
        grooveLength6.render(f5);
        corner2.render(f5);
        corner3.render(f5);
        corner4.render(f5);
        corner5.render(f5);
        corner6.render(f5);
        corner7.render(f5);
        corner8.render(f5);
        grovesBaseBend.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}